name: Spring Petclinic CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  DOCKER_IMAGE: docker.io/vinothbalakrish/petclinic-githubci
  JAVA_VERSION: '25'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build-and-test:
    name: Build & Test
    runs-on: [git]  # Use array format with labels
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
