
name: Spring Petclinic CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  DOCKER_IMAGE: docker.io/vinothbalakrish/petclinic-githubci
  JAVA_VERSION: '25'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build-and-test:
    name: Build & Test with Maven
    runs-on: [git]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        cache: 'maven'

    - name: Verify Java Version
      run: |
        echo "JAVA_HOME: $JAVA_HOME"
        java -version
        mvn -version

    - name: Build with Maven
      run: mvn clean package -DskipTests
    

    # - name: Run Tests
    #   run: mvn test


    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: petclinic-jar
        path: target/*.jar
        retention-days: 1
